---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - dpuconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - dpuconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - config.openshift.io
  resources:
  - dpuconfigs/status
  verbs:
  - get
  - patch
  - update
